# Generated by Django 4.1.1 on 2023-03-25 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('longURL', models.CharField(max_length=2048)),
                ('shortURL', models.CharField(max_length=50)),
            ],
        ),
    ]
