# Generated by Django 4.1.1 on 2023-03-25 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='id',
        ),
        migrations.AlterField(
            model_name='url',
            name='uid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
