# Generated by Django 4.1.1 on 2023-03-25 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_remove_url_id_alter_url_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='longURL',
            field=models.CharField(max_length=2048, unique=True),
        ),
        migrations.AlterField(
            model_name='url',
            name='shortURL',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
